spring:
  application:
    name: messages
  profiles:
    active: com
server:
  port: 9002

mybatis:
  mapper-locations: classpath:/mybatis/**/*Mapper.xml
  type-aliases-package: com.qy.shopmessages.model


#自定义值
messages:
  #邮件队列
  mail_queue: mail_queue