server:
  port: 9002

spring:
  application:
    name: messages
  #数据库连接信息
  datasource:
    name: messages
    url: jdbc:mysql://10.10.64.115:3306/shop
    username: root
    password: purang
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

    mybatis:
      mapper-locations: classpath:/mybatis/**/*Mapper.xml

  activemq:
    broker-url: tcp://localhost:61616
    in-memory: true
    pool:
      enabled: false
  jms:
    pub-sub-domain: false # 开启topic订阅，不开启就是queue

  mail:
    host: smtp.qq.com
    username: yushengjun644064@163.com
    password: itmayiedu644






#自定义值
messages:
  #邮件队列
  mail_queue: mail_queue