spring:
  #数据库连接信息
  datasource:
    name: messages
    url: jdbc:mysql://localhost:3306/shop
    username: root
    password: root
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
  activemq:
    broker-url: tcp://localhost:61616  #Web管理界面默认端口8161
    in-memory: true
    pool:
      enabled: false
  jms:
    pub-sub-domain: false # 开启topic订阅，不开启就是queue
  mail:
    host: smtp.qq.com
    username: 1114260199@qq.com
    password: afgdunirlmfibacd